#lang racket
(define (modexp x y n)
  (cond ((= y 0) 1)
        ((= (remainder y 2) 0) (modexp (modulo (* x x) n) (/ y 2)n))
        (#t (modulo (* x (modexp x (- y 1) n)) n))))
(define (is-prime n)
  (define x (random n))
  (cond ((< n 2) #f)
        ( (= x 0) (is-prime n))
        ( (= (modexp x (- n 1) n) 1) #t)
        ( #t #f)))
(define (goldbach m)
  (cond ((and (= (remainder m 2) 1) (is-prime (- m 2))) 1)
        (#t (goldeven m 3))))
(define (goldeven m n)
  (cond ((= m 4) (cons 2 2))
        ( (and (is-prime n) (is-prime (- m n))) (cons n (- m n)))
        ( #t (goldeven m (+ n 2)))))